apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: orderflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: codsubayi/notification-service:1487a4b
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: orderflow
            - name: POSTGRES_USER
              value: orderflow
            - name: POSTGRES_PASSWORD
              value: orderflowpass

            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: orderflow
            - name: RABBITMQ_PASSWORD
              value: orderflowpass

            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: orderflow
spec:
  selector:
    app: notification-service
  ports:
    - port: 8082
      targetPort: 8082