apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: orderflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: codsubayi/order-api:1487a4b
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: orderflow
            - name: POSTGRES_USER
              value: orderflow
            - name: POSTGRES_PASSWORD
              value: orderflowpass

            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: orderflow
            - name: RABBITMQ_PASSWORD
              value: orderflowpass

            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: orderflow
spec:
  selector:
    app: order-api
  ports:
    - port: 8080
      targetPort: 8080